autoInstallPeers: true
ignoreWorkspaceRootCheck: true
strictPeerDependencies: false
minimumReleaseAgeExclude:
  - '@vitest/expect@4.1.8'
  - '@vitest/mocker@4.1.8'
  - '@vitest/pretty-format@4.1.8'
  - '@vitest/runner@4.1.8'
  - '@vitest/snapshot@4.1.8'
  - '@vitest/spy@4.1.8'
  - '@vitest/utils@4.1.8'
  - lint-staged@17.0.7
  - vite@8.0.15
  - vitest@4.1.8
shamefullyHoist: true
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - packages/*

patchedDependencies:
  '@arethetypeswrong/cli': patches/@arethetypeswrong__cli.patch

allowBuilds:
  esbuild: true
  simple-git-hooks: true
catalog:
  '@primeuix/themes': ^2.0.3
  '@primevue/auto-import-resolver': ^4.5.5
  primevue: ^4.5.5
catalogs:
  cli:
    '@antfu/eslint-config': ^9.0.0
    '@antfu/ni': ^30.1.0
    '@arethetypeswrong/cli': 0.17.1
    bumpp: ^11.1.0
    eslint: ^10.4.1
    esno: ^4.8.0
    lint-staged: ^17.0.7
    pnpm: ^11.5.2
    premove: ^4.0.0
    simple-git-hooks: ^2.13.1
    taze: ^19.14.1
    tsdown: ^0.22.2
    vite: ^8.0.16
    vitest: ^4.1.8
    vue-tsc: ^3.3.3

  icons:
    '@iconify-json/akar-icons': ^1.2.7
    '@iconify-json/carbon': ^1.2.23
    '@iconify-json/fluent-emoji': ^1.2.7
    '@iconify-json/logos': ^1.2.11
    '@iconify/utils': ^3.1.3

  playground:
    '@vitejs/plugin-vue': ^6.0.7
    '@vueuse/core': ^14.3.0
    chart.js: ^4.5.1
    gsap: ^3.15.0
    prettier: ^3.8.3
    shiki: ^4.2.0
    unplugin-auto-import: ^21.0.0
    unplugin-vue: ^7.2.0
    unplugin-vue-components: ^32.1.0
    vue: ^3.5.35

  types:
    '@types/node': ^25.9.2
    '@types/prettier': ^3.0.0
    typescript: ^6.0.3

  uno:
    unocss: ^66.7.0
    unocss-preset-useful: ^1.0.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
