packages:
  - playground
  - docs
  - talk
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^3.12.0
  '@antfu/ni': ^0.23.1
  '@iconify-json/akar-icons': ^1.2.1
  '@iconify-json/carbon': ^1.2.4
  '@iconify-json/fluent-emoji': ^1.2.1
  '@iconify-json/logos': ^1.2.3
  '@iconify/utils': ^2.2.0
  '@slidev/cli': 0.49.23
  '@slidev/client': 0.49.23
  '@types/node': ^22.10.2
  '@types/prettier': ^3.0.0
  '@unocss/preset-mini': ^0.65.1
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^12.0.0
  '@vueuse/shared': ^12.0.0
  bumpp: ^9.9.1
  chart.js: ^4.4.7
  eslint: ^9.16.0
  esno: ^4.8.0
  lint-staged: ^15.2.11
  pnpm: ^9.15.0
  prettier: ^3.4.2
  rimraf: ^6.0.1
  shiki: ^1.24.2
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  typescript: ^5.7.2
  unbuild: ^2.0.0
  unocss: ^0.65.1
  unocss-preset-useful: ^0.9.1
  unplugin-auto-import: ^0.19.0
  unplugin-vue-components: ^0.27.5
  vite: ^6.0.3
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-tsc: ^2.1.10
