packages:
  - playground
  - docs
  - talk
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@antfu/ni': ^24.3.0
  '@arethetypeswrong/cli': 0.17.1
  '@iconify-json/akar-icons': ^1.2.2
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/fluent-emoji': ^1.2.3
  '@iconify-json/logos': ^1.2.4
  '@iconify/utils': ^2.3.0
  '@slidev/cli': 0.49.23
  '@slidev/client': 0.49.23
  '@types/node': ^22.14.1
  '@types/prettier': ^3.0.0
  '@unocss/preset-mini': ^66.1.0-beta.12
  '@vitejs/plugin-vue': ^5.2.3
  '@vueuse/core': ^13.1.0
  '@vueuse/shared': ^13.1.0
  bumpp: ^10.1.0
  chart.js: ^4.4.9
  eslint: ^9.25.1
  esno: ^4.8.0
  lint-staged: ^15.5.1
  pnpm: ^10.9.0
  prettier: ^3.5.3
  rimraf: ^6.0.1
  shiki: ^3.3.0
  simple-git-hooks: ^2.12.1
  taze: ^19.0.4
  tsdown: ^0.9.5
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.1.0-beta.12
  unocss-preset-useful: ^0.9.2
  unplugin-auto-import: ^19.1.2
  unplugin-vue-components: ^28.5.0
  vite: ^6.3.2
  vitest: ^3.1.2
  vue: ^3.5.13
  vue-tsc: ^2.2.10
