packages:
  - playground
  - packages/*

catalogs:
  cli:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    '@arethetypeswrong/cli': 0.17.1
    bumpp: ^10.3.1
    eslint: ^9.39.1
    esno: ^4.8.0
    lint-staged: ^16.2.7
    pnpm: ^10.23.0
    premove: ^4.0.0
    simple-git-hooks: ^2.13.1
    taze: ^19.9.0
    tsdown: ^0.16.7
    vite: ^7.2.4
    vitest: ^4.0.14
    vue-tsc: ^3.1.5

  icons:
    '@iconify-json/akar-icons': ^1.2.7
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/fluent-emoji': ^1.2.7
    '@iconify-json/logos': ^1.2.10
    '@iconify/utils': ^3.0.2

  playground:
    '@vitejs/plugin-vue': ^6.0.2
    '@vueuse/core': ^14.0.0
    chart.js: ^4.5.1
    gsap: ^3.13.0
    prettier: ^3.6.2
    shiki: ^3.15.0
    unplugin-auto-import: ^20.2.0
    unplugin-vue: ^7.0.8
    unplugin-vue-components: ^30.0.0
    vue: ^3.5.25
    vue-tsc: ^3.1.5

  types:
    '@types/node': ^24.10.1
    '@types/prettier': ^3.0.0
    typescript: ^5.9.3

  uno:
    unocss: ^66.5.9
    unocss-preset-useful: ^1.0.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

autoInstallPeers: true
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
strictPeerDependencies: false
