/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Item: typeof import('./components/ListColor.vue')['default']
    ListColor: typeof import('./components/ListColor.vue')['default']
    Toggle: typeof import('./components/Toggle.vue')['default']
  }
}
