/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Controls: typeof import('./components/Palette/PaletteControls.vue')['default']
    Item: typeof import('./components/ListColor.vue')['default']
    ListColor: typeof import('./components/ListColor.vue')['default']
    Palette: typeof import('./components/Palette/index.vue')['default']
    PaletteAlpha: typeof import('./components/Palette/PaletteAlpha.vue')['default']
    PaletteControls: typeof import('./components/Palette/PaletteControls.vue')['default']
    PalettePanel: typeof import('./components/Palette/PalettePanel.vue')['default']
    Picker: typeof import('./components/Picker.vue')['default']
    Toggle: typeof import('./components/Toggle.vue')['default']
  }
}
