import type { ColorType } from '@magic-color/transformer'
import {
  hexToHsb,
  hexToHsl,
  hexToLab,
  hexToLch,
  hexToOklab,
  hexToOklch,
  hexToRgb,

  hsbToHex,
  hsbToHsl,
  hsbToLab,
  hsbToLch,
  hsbToOklab,
  hsbToOklch,
  hsbToRgb,

  hslToHex,
  hslToHsb,
  hslToLab,
  hslToLch,
  hslToOklab,
  hslToOklch,
  hslToRgb,

  labToHex,
  labToHsb,
  labToHsl,
  labToLch,
  labToOklab,
  labToOklch,
  labToRgb,

  lchToHex,
  lchToHsb,
  lchToHsl,
  lchToLab,
  lchToOklab,
  lchToOklch,
  lchToRgb,

  oklabToHex,
  oklabToHsb,
  oklabToHsl,
  oklabToLab,
  oklabToLch,
  oklabToOklch,
  oklabToRgb,

  oklchToHex,
  oklchToHsb,
  oklchToHsl,
  oklchToLab,
  oklchToLch,
  oklchToOklab,
  oklchToRgb,

  rgbToHex,
  rgbToHsb,
  rgbToHsl,
  rgbToLab,
  rgbToLch,
  rgbToOklab,
  rgbToOklch,
} from '@magic-color/transformer'

// 颜色转换映射表
type ConversionFunction = (color: any) => any

export const CONVERSION_MAP: Record<string, Partial<Record<ColorType, ConversionFunction>>> = {
  hex: {
    rgb: hexToRgb,
    hsl: hexToHsl,
    hsb: hexToHsb,
    lab: hexToLab,
    lch: hexToLch,
    oklab: hexToOklab,
    oklch: hexToOklch,
  },
  keyword: {
    rgb: hexToRgb,
    hsl: hexToHsl,
    hsb: hexToHsb,
    lab: hexToLab,
    lch: hexToLch,
    oklab: hexToOklab,
    oklch: hexToOklch,
  },
  rgb: {
    hex: rgbToHex,
    hsl: rgbToHsl,
    hsb: rgbToHsb,
    lab: rgbToLab,
    lch: rgbToLch,
    oklab: rgbToOklab,
    oklch: rgbToOklch,
  },
  hsl: {
    hex: hslToHex,
    rgb: hslToRgb,
    hsb: hslToHsb,
    lab: hslToLab,
    lch: hslToLch,
    oklab: hslToOklab,
    oklch: hslToOklch,
  },
  hsb: {
    hex: hsbToHex,
    rgb: hsbToRgb,
    hsl: hsbToHsl,
    lab: hsbToLab,
    lch: hsbToLch,
    oklab: hsbToOklab,
    oklch: hsbToOklch,
  },
  lab: {
    hex: labToHex,
    rgb: labToRgb,
    hsl: labToHsl,
    hsb: labToHsb,
    lch: labToLch,
    oklab: labToOklab,
    oklch: labToOklch,
  },
  lch: {
    hex: lchToHex,
    rgb: lchToRgb,
    hsl: lchToHsl,
    hsb: lchToHsb,
    lab: lchToLab,
    oklab: lchToOklab,
    oklch: lchToOklch,
  },
  oklab: {
    hex: oklabToHex,
    rgb: oklabToRgb,
    hsl: oklabToHsl,
    hsb: oklabToHsb,
    lab: oklabToLab,
    lch: oklabToLch,
    oklch: oklabToOklch,
  },
  oklch: {
    hex: oklchToHex,
    rgb: oklchToRgb,
    hsl: oklchToHsl,
    hsb: oklchToHsb,
    lab: oklchToLab,
    lch: oklchToLch,
    oklab: oklchToOklab,
  },
}

// 颜色通道映射表
export const CHANNEL_MAP: Record<string, readonly string[]> = {
  rgb: ['r', 'g', 'b'],
  hsl: ['h', 's', 'l'],
  hsb: ['h', 's', 'b'],
  lab: ['l', 'a', 'b'],
  lch: ['l', 'c', 'h'],
  oklab: ['l', 'a', 'b'],
  oklch: ['l', 'c', 'h'],
} as const
